producto/urls.py
from django.urls import path
from producto.views import *

urlpatterns = [
    path('grupo_list/', GrupoListView.as_view(), name='grupo_list'),
    path('grupo_create/', GrupoCreateView.as_view(), name='grupo_create'),
    path('grupo_edit/<int:pk>/', GrupoUpdateView.as_view(), name='grupo_edit'),
    path('existencia/grupo/', existencia_grupo, name='existencia_grupo'),

    path('insumo_list/<pk>/<nombre>/', InsumoListView.as_view(), name='insumo_list'),
    path('insumo_create/<pk1>/<nombre>/', InsumoCreateView.as_view(), name='insumo_create'),
    path('insumo_edit/<pk>/<pk1>/<nombre>/', InsumoEditView.as_view(), name='insumo_edit'),
    path('existencia/insumo/', existencia_insumo, name='existencia_insumo'),

    path('producto_list/', producto_list.as_view(), name='producto_list'),
    path('crea_producto/', crea_producto.as_view(), name='crea_producto'),
    path('mod_producto/<pk>/', mod_producto.as_view(), name='mod_producto'),
    path('elimina_producto/<pk>/', elimina_producto, name='elimina_producto'),
    path('existencia/producto/', existencia_producto, name='existencia_producto'),
    path('lista/', lista, name='lista'),
    
    path('paquete_list/', paquete_list.as_view(), name='paquete_list'),
    path('crea_paquete/', crea_paquete.as_view(), name='crea_paquete'),
    path('mod_paquete/<pk>/', mod_paquete.as_view(), name='mod_paquete'),
    path('existencia/paquete/', existencia_paquete, name='existencia_paquete'),
]

producto/models.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import models
from django.db.models import F
from django.db.models import Case, When, Value, CharField

from core.models import ACTIVO_PRODUCTO, TIPO_PRODUCTO, TIPO, SINO, TIPO_SOLICITUD

class Grupo(models.Model, PermissionRequiredMixin):
    nombre = models.CharField("Nombre", max_length=255)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_PRODUCTO, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Grupo'
        verbose_name_plural = 'Grupos'
        ordering = ['nombre']
        unique_together = ['nombre']
        db_table = 'Grupo'

    def __str__(self):
        return '%s' % (self.nombre)

class Insumo(models.Model, PermissionRequiredMixin):
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE, related_name="insumo_grupo")
    nombre = models.CharField("Nombre", max_length=255)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_PRODUCTO, default=1)
    imagen = models.IntegerField("Imagen insumo.", null=True, blank=True)
    precio = models.DecimalField("Precio", max_digits=10, decimal_places=2, default=0)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Insumo'
        verbose_name_plural = 'Insumos'
        ordering = ['grupo', 'nombre']
        unique_together = ['grupo', 'nombre']
        db_table = 'Insumo'

    def __str__(self):
        return f"{self.grupo.nombre} - {self.nombre}"

class Producto(models.Model, PermissionRequiredMixin):
    nombre = models.CharField("Nombre", max_length=255)
    breve = models.CharField("Breve descripción", max_length=255, null=True, blank=True)
    tipo = models.IntegerField("Tipo", choices=TIPO_PRODUCTO, default=1)
    insumos = models.JSONField("Ingredientes", null=True, blank=True)
    precio = models.DecimalField("Precio", max_digits=10, decimal_places=2, default=0)
    imagen = models.IntegerField("Imagen prod.", null=True, blank=True)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_PRODUCTO, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['tipo','nombre',]
        unique_together = ['nombre']
        db_table = 'Producto'

    def __str__(self):
        return ' %s, %s, $ %s' % (dict(TIPO_PRODUCTO).get(self.tipo), self.nombre, self.precio)

class Paquete(models.Model, PermissionRequiredMixin):
    nombre = models.CharField("Promoción", max_length=255)
    descripcion = models.CharField("Descripción", max_length=255, null=True, blank=True)
    tipo = models.IntegerField("Tipo", choices=TIPO, default=1)
    componentes = models.JSONField("Componentes", null=True, blank=True)
    precio = models.DecimalField("Precio", max_digits=10, decimal_places=2, default=0)
    imagen = models.IntegerField("Imagen paq.", null=True, blank=True)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_PRODUCTO, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Paquete'
        verbose_name_plural = 'Paquetes'
        ordering = ['tipo', 'nombre',]
        db_table = 'Paquete'

    def __str__(self):
        return ' %s, $ %s, %s' % (self.nombre, self.precio, dict(ACTIVO_PRODUCTO).get(self.estatus))

producto/forms.py
from decimal import Decimal
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import NumberInput
import decimal
import json

from .models import *

class CommaSeparatedNumberInput(forms.TextInput):
    def format_value(self, value):
        if value is None:
            return ''
        # Convertir el valor a una cadena con separadores de miles
        value = '{:,.2f}'.format(value)
        # Reemplazar el punto decimal por una coma
        value = value.replace('.', ',')
        return value

class GrupoForm(forms.ModelForm):
    class Meta:
        model = Grupo
        fields = ['nombre', 'estatus']

class InsumoForm(forms.ModelForm):
    class Meta:
        model = Insumo
        fields = ['grupo', 'nombre', 'precio', 'estatus']

class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = [
            'nombre',
            'breve',
            'tipo',
            'precio',]
        labels = {
            'nombre': 'Nombre',
            'breve': 'Breve descripción',
            'tipo': 'Tipo',
            'precio': 'Precio',}
        widgets = {
            'nombre':forms.TextInput(),
            'breve':forms.Textarea(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nombre'].required = True
        self.fields['breve'].required = False
        self.fields['tipo'].required = False
        self.fields['precio'].required = False
    
    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if not nombre:
            raise forms.ValidationError("Tecleé la nombre del consumo")
        else:
            instance = self.instance
            id = instance.id
            existe = Producto.objects.filter(nombre=nombre).exclude(id=id).first()
            if existe:
                raise forms.ValidationError("El producto ya existe")
        return nombre

    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if not precio:
            raise forms.ValidationError("Tecleé precio del consumo")
        elif precio <= 0:
            raise forms.ValidationError("El precio debe ser mayor a cero")
        return decimal.Decimal(precio)

class PaqueteForm(forms.ModelForm):
    data = forms.CharField(widget=forms.HiddenInput(), required=True)

    class Meta:
        model = Paquete
        fields = [
            'nombre',
            'descripcion',
            'tipo',
            'precio',
            'estatus']
        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Descripción',
            'tipo': 'Tipo',
            'precio': 'Precio',
            'estatus': 'Estatus'}
        widgets = {
            'nombre':forms.TextInput(),
            'descripcion':forms.Textarea(attrs={'rows': '4'}),
            'precio': forms.TextInput(attrs={'input': '99,999,999.99'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nombre'].required = False
        self.fields['descripcion'].required = False
        self.fields['tipo'].required = False
        self.fields['precio'].required = False
        self.fields['estatus'].required = False
    
    def clean_tipo(self):
        tipo = self.cleaned_data.get('tipo')
        return tipo

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if not nombre:
            raise forms.ValidationError("Tecleé la nombre")
        return nombre

    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if not precio:
            raise forms.ValidationError("Tecleé precio del consumo")
        return decimal.Decimal(precio)

    def clean(self):
        cleaned_data = super().clean()
        data = cleaned_data.get('data')
        if data:
            try:
                json_data = json.loads(data)
                if not json_data:
                    raise forms.ValidationError('Debe proporcionar al menos un producto')
            except json.JSONDecodeError:
                raise forms.ValidationError('Error de formato JSON en el campo "data"')
        else:
            raise forms.ValidationError('No existe data')
        return cleaned_data

producto/templates/producto/insumo_form.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
<div class="row d-flex justify-content-center" style="padding: 20px;">
    <div class="cuadro col-11 col-xs-10 col-sm-10 col-md-8 col-lg-7 col-xl-6 col-xxl-5 text-center">
        <h1>{{ accion }} Insumos ({{ nombre }})</h1>
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-12" hidden>
                    {{ form.grupo|as_crispy_field }}
                </div>
                <div class="col-12 text-center row">
                    <div class="col-8 mx-auto"> <!-- Agregamos mx-auto para centrar -->
                        {{ form.nombre|as_crispy_field }}
                    </div>
                    <div class="col-4"> <!-- Agregamos mx-auto para centrar -->
                        <label for="id_precio"></label><br>
                        <input type="text" name="precio" id="id_precio" class="form-control"
                        onfocusout="reformatear('id_precio')" onkeypress="return valideKey(event);">
                    </div>
                </div>
                <div class="col-12" hidden>
                    {{ form.estatus|as_crispy_field }}
                </div>
            </div>
            <br>
            <div class="row col-12">
                <div class="col-6 text-center">
                    <button type="submit" class="btn btn-info cuadro-boton">Guardar</button>
                </div>
                <div class="col-6 text-center">
                    <a href="{% url 'insumo_list' pk1 nombre %}" class="btn btn-info cuadro-boton">Regresar</a>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    valor='{{registro.precio}}'.replaceAll(',','');
    $("#id_precio").focus().css("text-align", "right").val(valor);
    $(document).ready(function () {
        $("#id_nombre").focus();
    });
</script>
{% endblock %}

producto/templates/producto/paquete.html
{% extends "core/base.html" %}
{{ form.media }}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block estilo %}
<style>
    .checkbox-large.form-check-input {
        width: 25px;
        height: 25px;
        margin-right: 25px;
    }
</style>
{% endblock %}
{% block contenido %}
<div class="row d-flex justify-content-center">
    <div class="col-8 col-xs-7 col-sm-7 col-md-5 col-lg-4 col-xl-3 col-xxl-3 text-center">
        <h2 class="cuadro">Combo-Promoción</h2>
    </div>
</div>
<div class="text-center">
    <h4 style="color: rgb(11, 125, 231);">{{accion}}</h4>
    <div class="container cuadro col-11 col-xs-9 col-sm-9 col-md-9 col-lg-8 col-xl-7 col-xxl-6">
        <form method="POST" id="formulario">
            {% csrf_token %}
            <div class="row d-flex justify-content-around" style="margin-top: 10px;">
                <button type="submit" class="btn btn-info cuadro-boton col-5">Guarda</button>
                <a href="{% url 'paquete_list' %}" class="btn btn-info cuadro-boton col-5">Regresar</a>
            </div>
            <br>
            <div class="col-12">
                {{form.nombre|as_crispy_field}}
            </div>
            <div class="col-12">
                {{form.descripcion|as_crispy_field}}
            </div>
            <div class="d-flex justify-content-center">
                <div class="col-6">
                    {{form.tipo|as_crispy_field}}
                </div>
                <div class="col-5">
                    {{form.precio|as_crispy_field}}
                </div>
            </div>
            <hr>
            <div class="row d-flex justify-content-center col-12">
                <div class="col-12">
                    <label>Producto</label>
                    <select name="producto" id="id_producto" class="form-control">
                        <option value=0>---------</option>
                        {% for p in producto_cmb %}
                        <option value="{{ p.id }}">{{ p.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row d-flex justify-content-center col-12">
                <div class="col-3" id="gpo_cantidad">
                    <label for="id_cantidad">Cantidad</label>
                    <input type="text" class="form-control" name="cantidad" id="id_cantidad" style="text-align: center;"
                        onfocusout="reformatear('id_cantidad')" onkeypress="return valideKey(event);">
                </div>
                <div class="col-2">
                    <button type="button" class="btn btn-info cuadro-boton" onclick="agrega()"
                        id="id_agregar" style="margin-top: 20px;">Agrega</button>
                </div>
            </div>
            <div id="opciones">

            </div>
            <div>
                <div class="col-12 d-flex justify-content-center row">
                    <table class="table table-striped caption-top col-12 is-invalid" id="id_componentes">
                        <caption>
                            <h3>Contenido</h3>
                        </caption>
                        <thead>
                            <tr>
                                <th style="text-align: center;" hidden>id</th>
                                <th class="col-7" style="text-align: center;">Producto</th>
                                <th class="col-4" style="text-align: center;">Cantidad</th>
                                <th class="col-1" style="text-align: center;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for paquete in componentes %}
                                {% for producto in paquete.componentes %}
                                <tr>
                                    <td hidden>{{ producto.id }}</td>
                                    <td class="text-start">{{ producto.nombre }}</td>
                                    <td >{{ producto.cantidad }}</td>
                                    <td >
                                        <button class="delete-button col-1 fondo-transparente btn-elimina" style="border: none;">
                                            <img src="{% static 'core/img/eliminar.svg' %}" alt="Eliminar" 
                                                class="delete-icon fondo-transparente" style="width: 15px; height: 15px">
                                        </button>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% endfor %}
                        </tbody>
                    </table>
                    {% for error in form.non_field_errors %}
                    <p id="error_1_id_componentes" class="invalid-feedback col-12"><strong>{{ error }}</strong></p>
                    {% endfor %}
                </div>
            </div>
            <hr>
            <div class="row d-flex justify-content-around">
                <button type="submit" class="btn btn-info cuadro-boton col-5">Guarda</button>
                <a href="{% url 'producto_list' %}" class="btn btn-info cuadro-boton col-5">Regresar</a>
            </div>
            <input type="text" class="form-control" name="data" id="id_data" hidden>
        </form>
    </div>
</div>
<script>
    $('.btn-elimina').on('click', function() {
        event.preventDefault();
        $(this).closest('tr').remove();
    });
    var accion = "{{accion}}";
    $('#id_precio').on('focusout', function () {
        reformatear('id_precio');
    });
    $('#id_precio').on('keypress', function (event) {
        return valideKey(event);
    });
    function agrega() {
        $("#id_agregar").attr('disabled', true);
        var select = $('#id_producto');
        var tabla = $('#id_componentes');
        var nuevoTr = $('<tr>');
        var nuevoTd1 = $('<td hidden>').text($("#id_producto").val()).addClass('col-1');
        var nuevoTd2 = $('<td>').text(select.find('option:selected').text()).addClass('col-5 text-start');
        var nuevoTd3 = $('<td>').text($("#id_cantidad").val()).addClass('col-3');
        nuevoTr.append(nuevoTd1);
        nuevoTr.append(nuevoTd2);
        nuevoTr.append(nuevoTd3);
    
        var nuevoTd4 = $('<td>').addClass('col-1');
        var $deleteButton = $("<button>", {
            class: "delete-button col-1 fondo-transparente btn-elimina"
        }).css({
            border: "none",
        });
        var $deleteIcon = $("<img>", {
            src: "{% static 'core/img/eliminar.svg' %}",
            alt: "Eliminar",
            class: "delete-icon fondo-transparente"
        }).css({
            width: "15px",
            height: "15px",
        });            
        $deleteButton.empty().append($deleteIcon);
        nuevoTd4.append($deleteButton);
        nuevoTr.append(nuevoTd4);
        tabla.find('tbody').append(nuevoTr);
        $("#id_producto").val(0);
        $("#id_cantidad").val(0);
    }
    $('#id_cantidad').on('keyup', function () {
        validacion();
    });
    $('#id_producto').change(function () {
        validacion();
    });
    function validacion() {
        opcion = $("#id_producto").val();
        cantidad = $("#id_cantidad").val();
        if (opcion == "" || opcion == 0 || cantidad == "" || cantidad == 0) {
            $("#id_agregar").attr('disabled', true);
        } else {
            var tabla = $('#id_componentes');
            $("#id_agregar").attr('disabled', false);
            tabla.find('tr').each(function() {
                if ($(this).find('td:eq(0)').text() == opcion) {
                    $("#id_agregar").attr('disabled', true);
                }
            });        
        }
    }
    $('#formulario').submit(function(event) {
        event.preventDefault();
    
        var jsonData = [];
    
        $('#id_componentes tbody tr').each(function() {
            var columna1Value = $(this).find('td:eq(0)').text();
            var columna2Value = $(this).find('td:eq(1)').text();
            var columna3Value = $(this).find('td:eq(2)').text();
    
            var rowData = {
                id: columna1Value,
                nombre: columna2Value,
                cantidad: columna3Value
            };
    
            jsonData.push(rowData);
        });
    
        var jsonStr = JSON.stringify(jsonData);
    
        $("#id_data").val(jsonStr);
    
        this.submit();
    });
    $(document).ready(function () {
        $("#id_precio").css("text-align", "right");
        $("#id_nombre").focus();
        $("#id_agregar").attr('disabled', true);
        $('#id_producto').change(function () {
            var selectedOption = $(this).find('option:selected');

        });
        $('#id_tipo').change(function () {
            var selectedOption = $(this).find('option:selected');
            if (selectedOption == 1) {
                
            } else if (selectedOption == 2) {

            } else if (selectedOption == 3) {

            }
        });
    });
</script>
{% endblock %}

producto/templates/producto/paquete_list.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
<div class="container sin-cuadro col-12 col-xs-10 col-sm-10 col-md-10 col-lg-9 col-xl-8 col-xxl-8 text-center">
    <div class="row d-flex justify-content-center">
        {% if catalogo_agregar_perm %}
        <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-4 col-xl-4 col-xxl-3 text-center">
            <a href="{% url 'crea_paquete' %}" class="btn btn-info cuadro-boton">Nueva Promo-Combo</a>
        </div>
        {% endif %}
        <div class="col-4 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
            <a href="{% url 'producto_list' %}" class="btn btn-info cuadro-boton">Regresar</a>
        </div>
    </div>
</div>
<div>
    <div class="container cuadro col-11 col-xs-10 col-sm-10 col-md-7 col-lg-6 col-xl-6 col-xxl-5">
        <form method="POST">
            {% csrf_token %}
            <div>
                <div class="col-12">
                    <table class="table table-striped caption-top">
                        <caption>
                            <h3>Promos y Combos</h3>
                        </caption>
                        <thead>
                            <tr class="text-center">
                                <th class="col-6">
                                    Nombre
                                </th>
                                <th class="col-2">
                                    Tipo
                                </th>
                                <th class="col-2">
                                    Precio
                                </th>
                                <th class="col-1">
                                    Estatus
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for promos in paquetes %}
                            <tr>
                                <td>
                                    {% if catalogo_modificar_perm %}
                                    <a href="{% url 'mod_paquete' promos.id %}"
                                        style="text-decoration: none; font-weight: bold; font-style: italic;">
                                        {{ promos.nombre }}
                                    </a>
                                    {% else %}
                                    <a href="#" style="text-decoration: none; ">
                                        {{ promos.nombre }}
                                    </a>
                                    {% endif %}
                                </td>
                                <td>
                                    {{ promos.get_tipo_display }}
                                </td>
                                <td class="text-end">
                                    {{ promos.precio }}
                                </td>
                                <td class="align-middle">
                                    <input type="checkbox" name="existe_{{ promos.id }}" id="id_existe_{{ promos.id }}" 
                                        {% if promos.estatus %} checked {% endif %} class="form-check-input checkbox-large existencia" 
                                        style="margin-left: 10px;" 
                                        {% if not catalogo_modificar_perm %}
                                        disabled
                                        {% endif %}
                                        >
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(".existencia").on("change", function () {
            var checkboxId = $(this).attr("id");
            var paqueteId = checkboxId.split("_")[2];
            var isChecked = $(this).prop("checked");

            $.ajax({
                url: "/producto/existencia/paquete/", //
                method: "POST",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}", 
                    paquete_id: paqueteId,
                    isChecked: isChecked
                },
                success: function (response) {
                    
                },
                error: function (xhr, errmsg, err) {
                    
                }
            });
        });
    });
</script>
{% endblock %}

producto/templates/producto/producto.html
{% extends "core/base.html" %}
{{ form.media }} 
{% load static %} 
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %} 
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %} 
{% endblock %}
{% block contenido %} 
{% if user.is_authenticated %} 
{% if catalogo_agregar_perm or catalogo_modificar_perm %}
<div class="row d-flex justify-content-center">
  <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
    <h2 class="cuadro">Producto</h2>
  </div>
</div>
<div class="text-center">
  <h4 style="color: rgb(11, 125, 231)">{{accion}}</h4>
  <div class="container cuadro col-11 col-xs-9 col-sm-9 col-md-9 col-lg-8 col-xl-7 col-xxl-6">
    <form method="POST" class="row g-3" id="formulario">
      {% csrf_token %}
      <div class="row d-flex justify-content-around" style="margin-top: 10px">
        <button type="submit" class="btn btn-info cuadro-boton col-4">
          Guarda
        </button>
        <a href="{% url 'producto_list' %}"
          class="btn btn-info cuadro-boton col-4">
          Regresar
        </a>
      </div>
      <div class="col-12">{{form.nombre|as_crispy_field}}</div>
      <div class="col-4">{{form.tipo|as_crispy_field}}</div>
      <div class="col-4">{{form.precio|as_crispy_field}}</div>
      <div class="col-12">{{form.breve|as_crispy_field}}</div>
      <h3>Contenido</h3>
      <div class="row">
        <div class="row col-12 col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-9 col-xxl-9"
          id="seleccionados">
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="row col-12 col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-9 col-xxl-9">
          {% for insumo in insumos %}
          {% ifchanged insumo.grupo %}
          <div class="col-12 mt-3">
            <strong>{{ insumo.grupo }}</strong>
            <button type="button"
              class="btn btn-secondary"
              onclick="muestraOculta('grupo-{{ insumo.grupo_id }}')">
              Mostrar/Ocultar
            </button>
          </div>
          {% endifchanged %}
          <div class="col-4 mb-3 grupo-{{ insumo.grupo_id }}">
            <label for="insumo_{{ insumo.id }}">
              <input
                class="checkbox-insumo form-check-input checkbox-large"
                type="checkbox"
                id="insumo_{{ insumo.id }}"
                value="{{ insumo.id }}"/>
              {{ insumo.nombre }}
            </label>
          </div>
          {% if forloop.counter0|divisibleby:3 and not forloop.last %}
        </div>
        <div class="row col-12 col-xs-11 col-sm-11 col-md-11 col-lg-10 col-xl-9 col-xxl-9">
        {% endif %}
        {% endfor %}
        </div>
      </div>
      <div class="row d-flex justify-content-around">
        <button type="submit" class="btn btn-info cuadro-boton col-4">
          Guarda
        </button>
        <a href="{% url 'producto_list' %}"
          class="btn btn-info cuadro-boton col-4">
          Regresar
        </a>
      </div>
    </form>
  </div>
</div>
<script>
  var accion = "{{accion}}";
  $("#id_precio").on("focusout", function () {
    reformatear("id_precio");
  });
  $("#id_precio").on("keypress", function (event) {
    return valideKey(event);
  });
  function muestraOculta(ventana) {
    grupo = "." + ventana;
    rango = $(grupo);
    if (rango.is(":visible")) {
      rango.hide();
    } else {
      rango.show();
    }
  }
</script>
{% endif %}
{% endif %}
{% endblock %}

<script>
  $(document).ready(function () {
      {% block inicio %}
      if (accion = 'Modificación') {
          {% for producto in producto_insumos %}
              {% for insumo in producto.insumos %}
                  checkb = $('#insumo_' + {{insumo.id}});
                  checkb.prop("checked", true);
                  cambioCheckbox(checkb);
                  select = $('#tipo-' + {{insumo.id}});
                  select.val({{insumo.opcion}});
              {% endfor %}
          {% endfor %}
      }
      $(".checkbox-insumo").change(function() {
          cambioCheckbox($(this));
      });

      function cambioCheckbox (objeto) {
          // Obtiene el ID y el nombre del insumo
          var idInsumo = objeto.attr("id");
          var nombreInsumo = objeto.data("nombre-insumo");
          var label = objeto.closest("label");
          var labelText = label.text();
          var clave = objeto.val();
          var opciones = {{tipo_solicitud|safe}};

          // Verifica si el checkbox está marcado o desmarcado
          if (objeto.is(":checked")) {
              var grupo = $("<div class='col-6 row align-bottom' id='div-" + clave +  "'>");
              var select = $("<select class='form-select col-12' id='tipo-" + clave + "' name='ntipo-" + clave + "'>");

              opciones.forEach(function(opcion) {
                  var valor = opcion.key;
                  var texto = opcion.value;
                  select.append($('<option>', {
                      value: valor,
                      text: texto
                  }));
              });

              grupo.append(
                  "<div class='col-12' style='font-weight: bold;' id='seleccionado-" + clave + "'>"
                      + labelText
                      + "</div>"
              );

              grupo.append(select);

              $("#seleccionados").append(grupo);

          } else {
              $("#div-" + clave).remove();
          }
      }

      $("#id_precio").css("text-align", "right");
      $('#id_breve').attr('rows', '3');
      $("#id_nombre").focus();
      {% for grupo in grupos %}
          muestraOculta('grupo-{{ grupo.id }}');
      {% endfor %}
      {% endblock %}
  });
</script>