usuario/urls.py
from django.urls import path

from .views import *

urlpatterns = [
     path('usuarios/', usuarios.as_view(), name='usuarios'),
     path('registro/', registro, name='registro'),
     path('mod_usuario/<pk>/', UserUpdateView.as_view(), name='mod_usuario'),
]

usuario/models.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    celular = models.CharField(max_length=20, blank=True, null=True)
    cliente = models.BooleanField('Cliente', blank=True, null=True, default=False)
    
    class Meta:
        db_table = 'Usuario'

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import PasswordInput

from .models import Usuario

class UsuarioForm(UserCreationForm):
    cliente = forms.BooleanField(widget=forms.CheckboxInput)

    class Meta:
        model = Usuario
        fields = ['username', 'cliente', 'first_name', 'last_name', 'celular', 'email', 'password1', 'password2']
        labels = {
            'username': 'Usuario',
            'Cliente': 'Cliente',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'celular': 'Celular',
            'email': 'Correo',
            'password1': 'Contraseña',
            'password2': 'Confirmación'
            }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['cliente'].required = False
        self.fields['celular'].required = True
        self.fields['email'].required = True
        self.fields['password1'].required = False
        self.fields['password2'].required = False

class UsuarioFormEdit(forms.ModelForm):
    cliente = forms.BooleanField(widget=forms.CheckboxInput, label='')
    is_active = forms.BooleanField(widget=forms.CheckboxInput, label='')
    password = forms.CharField(
        widget=PasswordInput(attrs={'autocomplete': 'new-password'}),
        required=False,
        label='Nueva Contraseña'
    )

    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'cliente', 'celular', 'email', 'is_active', 'password']
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'cliente': 'Cliente',
            'celular': 'Celular',
            'email': 'Correo',
            'is_active': 'Activo',
            }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['cliente'].required = False
        self.fields['celular'].required = True
        self.fields['email'].required = True
        self.fields['is_active'].required = False

usuario/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash

from usuario.models import Usuario
from .forms import UsuarioForm, UsuarioFormEdit


class usuarios(LoginRequiredMixin, ListView):
    model = Usuario
    template_name = 'usuario/usuarios.html'
    context_object_name = 'usuarios'
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = Usuario.objects.exclude(username='iagevm').exclude(username='jcamarillo')
        # Puedes realizar filtros o manipulaciones adicionales en el queryset si es necesario
        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['usuarios_perm'] = self.request.user.has_perm('core.usuarios')
        context['crea_usuario_perm'] = self.request.user.has_perm('core.crea_usuario')
        context['modifica_usuario_perm'] = self.request.user.has_perm('core.modifica_usuario')
        return context

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = UsuarioFormEdit
    template_name = 'usuario/usuario.html'
    success_url = reverse_lazy('usuarios')  # URL de éxito después de guardar

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk', '0')
        usuario_sel = Usuario.objects.filter(id=pk).first()
        usuario = usuario_sel.username
        context['modifica_usuario_perm'] = self.request.user.has_perm('core.modifica_usuario')
        context['usuario'] = usuario
        return context

    def post(self, request, *args, **kwargs):
        # Intentar obtener el usuario a actualizar
        user = self.get_object()  # Obtén el usuario a actualizar

        # Obtener los datos del formulario manualmente
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        celular = request.POST.get('celular')
        email = request.POST.get('email')
        cliente = request.POST.get('cliente') == 'on'  # Checkbox devuelve 'on' o None
        is_active = request.POST.get('is_active') == 'on'  # Checkbox devuelve 'on' o None
        password = request.POST.get('password')

        # Actualizar los campos del usuario en la base de datos
        Usuario.objects.filter(id=user.id).update(
            first_name=first_name,
            last_name=last_name,
            celular=celular,
            email=email,
            cliente=cliente,
            is_active=is_active,
        )

        # Actualizar la contraseña solo si se proporciona un nuevo valor
        if password:
            user.set_password(password)  # Establece la nueva contraseña
            update_session_auth_hash(request, user)  # Mantiene la sesión activa

        user.save()  # Guarda el usuario para que se aplique la nueva contraseña

        return HttpResponseRedirect(reverse('usuarios'))

@login_required
def registro(request):
    data = {
        'form': UsuarioForm
    }
    if request.method == 'POST':
        formulario = UsuarioForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="usuarios")
        data["form"] = formulario
    return render(request, 'registration/registro.html', data)

usuario/templates/usuario/usuario.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated %}
{% if modifica_usuario_perm %}
<div class="row d-flex justify-content-center">
    <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
        <h3 class="cuadro">Usuario <strong>{{ usuario }}</strong></h3>
    </div>
</div>
<div>
    <div class="row d-flex justify-content-around text-center">
        <h4 style="color: rgb(11, 125, 231);">{{accion}}</h4>
    </div>
    <hr>
    <div class="container cuadro col-10 col-xs-9 col-sm-9 col-md-9 col-lg-8 col-xl-7 col-xxl-6">
        <form method="POST" class="row g-3">
            {% csrf_token %}
            <div class="col-12">
                {{form.first_name|as_crispy_field}}
            </div>
            <div class="col-12">
                {{form.last_name|as_crispy_field}}
            </div>
            <div class="col-6">
                {{form.celular|as_crispy_field}}
            </div>
            <div class="col-2" style="margin-left: 15px;">
                Activo
                <div class="col-12" style="margin-left: 7px; margin-top: 5px;">
                    {{form.is_active|as_crispy_field}}
                </div>
            </div>
            <div class="col-2" style="margin-left: 15px;">
                Cliente
                <div class="col-12" style="margin-left: 7px; margin-top: 5px;">
                    {{ form.cliente|as_crispy_field }}
                </div>
            </div>
            <div class="col-12">
                {{form.email|as_crispy_field}}
            </div>
            <div class="col-12">
                {{form.password|as_crispy_field}}
            </div>
            <hr>
            <div class="row d-flex justify-content-around">
                <button type="submit" class="btn btn-info cuadro-boton col-5">Guarda</button>
                <a href="{% url 'usuarios' %}" class="btn btn-info cuadro-boton col-5">Regresar</a>
            </div>
        </form>
    </div>
</div>
<script>
    $("#id_cliente").addClass('checkbox-large');
    $("#id_is_active").addClass('checkbox-large');
</script>
{% endif %}
{% endif %}
{% endblock %}

usuario/templates/usuario/usuario_confirm_delete.html
<h2>¿Estás seguro que deseas eliminar al usuario {{ object.username }}?</h2>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
    <a href="{% url 'usuarios' %}">Cancelar</a>
</form>

usuario/templates/usuario/usuarios.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated and usuarios_perm %}
<div class="d-flex justify-content-center">
    <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
        <h2 class="cuadro">Usuarios</h2>
    </div>
</div>
<div class="row d-flex justify-content-center" style="padding: 20px;">
    {% if crea_usuario_perm %}
    <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
        <a href="{% url 'registro' %}" class="btn btn-info cuadro-boton">Nuevo</a>
    </div>
    {% endif %}
    <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
        <a href="{% url 'index' %}" class="btn btn-info cuadro-boton">Regresar</a>
    </div>
</div>
<div class="d-flex justify-content-center">
    <div class="cuadro col-12 col-xs-11 col-sm-10 col-md-10 col-lg-9 col-xl-8 col-xxl-8">
        <table class="table table-striped" id="tabla-cocina">
            <thead>
                <tr class="text-center">
                    <th class="col-4">Nombre</th>
                    <th class="col-2">Usuario</th>
                    <th class="col-3">Correo</th>
                    <th class="col-2">Celular</th>
                    <th class="col-1"></th>
                </tr>
            </thead>
            <tbody>
                {% for user in usuarios %}
                <tr>
                    <td class="align-middle">
                        {% if modifica_usuario_perm %}
                        <a href="{% url 'mod_usuario' user.id %}" style="text-decoration: none; font-weight: bold; font-style: italic;">
                        {{ user.first_name }} {{ user.last_name }}
                        </a>
                        {% else %}
                        <a href="#" style="text-decoration: none; ">
                            {{ user.first_name }} {{ user.last_name }}
                        </a>    
                        {% endif %}
                    </td>
                    <td class="text-center align-middle">{{ user.username }}</td>
                    <td class="text-center align-middle">{{ user.email|default_if_none:"" }}</td>
                    <td class="text-center align-middle">{{ user.celular|default_if_none:"" }}</td>
                    <td class="align-middle">
                        <input class="form-check-input" type="checkbox" {% if user.cliente %}checked{% endif %} disable>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}