pedido/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('servicio/', servicio.as_view(), name='servicio'),
    path('comanda/', comanda.as_view(), name='comanda'),
    path('comanda_ver/<str:pk>/<int:tipo_pago>/', comanda_ver.as_view(), name='comanda_ver'),
    path('cancela_pedido/<int:id>/<int:tipo_pago>/', cancela_pedido, name='cancela_pedido'),
    path('valida_mesa/', valida_mesa.as_view(), name='valida_mesa'),
    path('comanda_detalle/<int:pk>/', comanda_detalle.as_view(), name='comanda_detalle'),
    path('cancela_producto/<int:id>/', cancela_producto, name='cancela_producto'),
    path('mod_insumos/<int:numero>/', mod_insumos, name='mod_insumos'),
    path('comanda_surte/<str:pk>/', comanda_surte.as_view(), name='comanda_surte'),
    path('cocina/', cocina.as_view(), name='cocina'),
    path('bar/', bar.as_view(), name='bar'),
    path('termina_cocina/<id>/', termina_cocina, name='termina_cocina'),
    path('cancela_prod/<id>/<pantalla>/', cancela_prod, name='cancela_prod'),
    path('termina_bar/<id>/', termina_bar, name='termina_bar'),
    path('cancela_producto_bar/<id>/', cancela_producto_bar, name='cancela_producto_bar'),
    path('cancela_producto_cocina/<id>/', cancela_producto_cocina, name='cancela_producto_cocina'),
    path('cancela_producto_entrega/<id>/', cancela_producto_entrega, name='cancela_producto_entrega'),
    path('entregas/', entregas.as_view(), name='entregas'),
    path('termina_entrega/<id>/', termina_entrega, name='termina_entrega'),
    path('cobranza/', cobranza.as_view(), name='cobranza'),
    path('reasignar/', reasignar.as_view(), name='reasignar'),
    path('mesas/', mesas, name='mesas'),
    path('cancela_producto_reasignar/<int:id>/', cancela_producto_reasignar, name='cancela_producto_reasignar'),    
    path('reasignar_producto/<id_comanda>/<id_producto>/', reasignar_producto, name='reasignar_producto'),
    path('pago_comanda/<str:pk>/', pago_comanda.as_view(), name='pago_comanda'),
    path('pago_productos/', pago_productos, name='pago_productos'),
    path('cierra/<pk>/', cierra, name='cierra'),
    

#    path('comanda_nueva/<str:mesa>/<str:observacion>/', comanda_nueva.as_view(), name='comanda_nueva'),
#    path('comanda_nueva/<str:mesa>/', comanda_nueva.as_view(), name='comanda_nueva'),
#    path('comanda_surte/<str:mesa>/<str:pk>/', comanda_surte.as_view(), name='comanda_surte'),
#    path('producto/', producto.as_view(), name='producto'),
#    path('obtener_json_producto/<int:producto_id>/', obtener_json_producto, name='obtener_json_producto'),
#    path('obtener_json_cerveza/<int:producto_id>/', obtener_json_cerveza, name='obtener_json_cerveza'),
#    path('obtener_json_escarcha/<int:producto_id>/', obtener_json_escarcha, name='obtener_json_escarcha'),
#    path('obtener_json_complemento/<int:producto_id>/', obtener_json_complemento, name='obtener_json_complemento'),
#    path('obtener_json_carne/<int:producto_id>/', obtener_json_carne, name='obtener_json_carne'),
#    path('obtener_json_sazonador/<int:producto_id>/', obtener_json_sazonador, name='obtener_json_sazonador#'),

#    path('cancela_elaborado/<id>/<pantalla>/', cancela_elaborado, name='cancela_elaborado'),
#    path('reasigna/<id>/<comanda>/', reasigna, name='reasigna'),
#    path('reasigna_act/', reasigna_act, name='reasigna_act'),
#    path('pago_productos/', pago_productos, name='pago_productos'),
#    path('cancela_comanda/<pk>/', cancela_comanda, name='cancela_comanda'),
#    path('cierra_comanda/<pk>/', cierra_comanda, name='cierra_comanda'),
#    path('comanda_cliente/', comanda_cliente.as_view(), name='comanda_cliente'),
#    path('asigna_comanda/<cliente>/<comanda>/', asigna_comanda, name='asigna_comanda'),
#    path('comanda_surte_cliente/<str:pk>/', comanda_surte_cliente.as_view(), name='comanda_surte_cliente'),

    
    
#    path('comandas/update-status/', update_comanda_status, name='update_comanda_status'),
]

pedido/models.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import models
from django.utils import timezone

from core.models import ACTIVA_COMANDA, ACTIVO_DETALLE, ACTIVO_PROMOCION, ACTIVO_CAJA
from producto.models import Producto
from usuario.models import Usuario
from core.models import Contable

def default_fecha_contable():
    contable = Contable.objects.filter(estatus=1).first()
    return contable.fecha if contable else timezone.now().date()

class Comanda(models.Model):
    mesa = models.CharField("Mesa", max_length=255, null=True, blank=True)
    observacion = models.CharField("Observación", max_length=255, null=True, blank=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioComanda", null=True, blank=True)
    usuario_cierra = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioComandaCierre", null=True, blank=True)
    usuario_cancela = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioComandaCancela", null=True, blank=True)
    usuario_cliente = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioComandaCliente", null=True, blank=True)
    estatus = models.IntegerField("Estatus", choices=ACTIVA_COMANDA, default=1)
    fecha_contable = models.DateField("Fecha Contable", default=default_fecha_contable)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Comanda'
        verbose_name_plural = 'Comandas'
        ordering = ['-fecha_alta',]
        db_table = 'Comanda'

    def __str__(self):
        return ' %s, %s, %s' % (self.mesa, self.observacion, dict(ACTIVA_COMANDA).get(self.estatus))


class Caja(models.Model, PermissionRequiredMixin):
    comanda = models.ForeignKey(Comanda, on_delete=models.CASCADE, verbose_name="Comanda")
    descripcion = models.CharField("Tipo", max_length=255)
    especifico = models.CharField("Descripción", max_length=255, null=True, blank=True)
    cantidad = models.IntegerField("Cantidad", default=1)
    precio_unitario = models.DecimalField("Precio unitario", max_digits=10, decimal_places=2, default=0)
    importe = models.DecimalField("Importe", max_digits=10, decimal_places=2, default=0)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_CAJA, default=1)
    usuario_elabora = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioCajaElabora", null=True, blank=True)
    usuario_cobra = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioCajaCobra", null=True, blank=True)
    usuario_cancela = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioCajaCancela", null=True, blank=True)
    descripcion_cancela = models.CharField("Descripción", max_length=255, null=True, blank=True)
    pago = models.ManyToManyField('Pago')
    fecha_contable = models.DateField("Fecha Contable", default=default_fecha_contable)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Operación'
        verbose_name_plural = 'Operaciones'
        ordering = ['comanda','-fecha_alta',]
        db_table = 'Caja'

    def __str__(self):
        return ' %s, %s, %s, %s' % (self.comanda, self.descripcion, self.importe, dict(ACTIVO_DETALLE).get(self.estatus))

class Pago(models.Model, PermissionRequiredMixin):
    importe_efectivo = models.DecimalField("Importe", max_digits=10, decimal_places=2, default=0)
    importe_tarjeta = models.DecimalField("Importe", max_digits=10, decimal_places=2, default=0)
    importe_transferencia = models.DecimalField("Importe", max_digits=10, decimal_places=2, default=0)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'
        ordering = ['-fecha_alta',]
        db_table = 'Pago'

class Detalle(models.Model, PermissionRequiredMixin):
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE, verbose_name="Caja")
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Producto")
    nom_paquete = models.CharField("Paquete", max_length=255, null=True, blank=True)
    nom_producto = models.CharField("Producto", max_length=255, null=True, blank=True)
    especifico = models.CharField("Especificación", max_length=255, null=True, blank=True)
    nota = models.CharField("Observación", max_length=255)
    especificacion = models.JSONField("Detalle", null=True, blank=True)
    cantidad = models.IntegerField("Cantidad", default=1)
    precio_unitario = models.DecimalField("Precio unitario", max_digits=10, decimal_places=2, default=0)
    importe = models.DecimalField("Importe", max_digits=10, decimal_places=2, default=0)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_DETALLE, default=1)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioDetalle", null=True, blank=True)
    usuario_elabora = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioDetalleElabora", null=True, blank=True)
    usuario_entrega = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioDetalleEntrega", null=True, blank=True)
    usuario_cobra = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioDetalleCobra", null=True, blank=True)
    usuario_cancela = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioDetalleCancela", null=True, blank=True)
    usuario_reasigna = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioDetalleReasigna", null=True, blank=True)
    fecha_contable = models.DateField("Fecha Contable", default=default_fecha_contable)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Detalle'
        verbose_name_plural = 'Detalles'
        ordering = ['caja','-fecha_alta',]
        db_table = 'Detalle'

    def __str__(self):
        return ' %s, %s, %s, %s' % (self.caja, self.nom_producto, self.importe, dict(ACTIVO_DETALLE).get(self.estatus))

pedido/templates/pedido/respaldo/comanda copy.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated %}
<style>
    .id-continuar.disabled {
        opacity: 0.5; /* Reduce la opacidad para indicar que está desactivado */
        pointer-events: none; /* Evita que se pueda hacer clic en el botón */
        /* Agrega otros estilos para reflejar visualmente el estado desactivado */
    }    
</style>
<div class="row d-flex justify-content-center">
    <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
        <h2 class="cuadro">Camanda</h2>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="container cuadro col-10 col-xs-9 col-sm-9 col-md-9 col-lg-8 col-xl-7 col-xxl-6">
        <form method="POST" class="row g-3">
            {% csrf_token %}
            <div class="col-4">
                {{form.mesa|as_crispy_field}}
                <label style="color: red;" id="error_mesa"></label>
            </div>
            <div class="col-12">
                {{form.observacion|as_crispy_field}}
            </div>
            <hr>
            <div class="row d-flex justify-content-around">
                <a href="#" class="btn btn-info cuadro-boton col-5" id="id-continuar">Continuar</a>
                <a href="{% url 'servicio'  %}" class="btn btn-info cuadro-boton col-5">Regresar</a>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#id-continuar").addClass("disabled");
    });
    
    $('#id_mesa').on('keyup', function (event) {
        var id_mesa = $("#id_mesa").val().trim();
        $('#error_mesa').text('');
        $("#id-continuar").addClass("disabled");
        if (id_mesa.length > 0) {
            $.ajax({
                url: '/pedido/valida_mesa/',
                type: 'GET',
                data: {
                    id_mesa: id_mesa,
                },
                dataType: 'json',
                success: function (data) {
                    var existe = data.existe;
                    if (existe) {
                        $('#error_mesa').text('La mesa ya existe');
                    } else {
                        $("#id-continuar").removeClass("disabled");
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log('Error:', errorThrown);
                }
            });
        }
        $("#id-continuar").on("click", function(event) {
            event.preventDefault(); // Evita que se siga el enlace al hacer clic
            if (!$(this).hasClass("disabled")) {
                // Obtiene los valores de los campos del formulario
                var mesaVal = $("#id_mesa").val();
                var observacionVal = $("#id_observacion").val();
                // Construye la URL con los valores de los campos
                if (observacionVal == '') {
                    var url = "{% url 'comanda_nueva' 123 %}";
                    url = url.replace('123', mesaVal);
                } else {
                    var url = "{% url 'comanda_nueva' 123 456 %}";
                    url = url.replace('123', mesaVal);
                    url = url.replace('456', observacionVal);
                }
                // Redirecciona a la URL construida
                window.location.href = url;
            }
        });
    });
</script>
{% endblock %}

pedido/templates/pedido/respaldo/comanda_cliente.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% block headJS %}
<meta http-equiv="refresh" content="10">
{% endblock %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
<style>
    .no-border {
        border: none;
        /* Opcionalmente, puedes añadir otros estilos para mejorar la apariencia */
        outline: none;
        /* Elimina el contorno al enfocar el campo */
        box-shadow: none;
        /* Elimina cualquier sombra */
        font-size: 14px;
    }
</style>
<form>
    <div class="row d-flex justify-content-center" style="padding-top: 25px;">
        <div class="col-6 col-xs-5 col-sm-5 col-md-5 col-lg-3 col-xl-3 col-xxl-2 text-center">
            <a href="{% url 'index' %}" class="btn btn-info cuadro-boton">Regresar</a>
        </div>
    </div>
    <div class="row d-flex justify-content-center" style="padding-top: 25px; font-size: 20px; font-weight: bold;">
        <div class="col-3 col-xs-3 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-xxl-1 text-center">
            Por pagar<br>
            <input type="text" id="total_pago" readonly class="text-center no-border col-12" style="font-size: 20px; font-weight: bold; box-shadow: 0 0 10px #000;
                border-radius: 10px;" value="{{ importe_por_pagar.total_importe|default:0 }}">
        </div>
        <div class="col-3 col-xs-3 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-xxl-1 text-center">
            Pagado<br>
            <input type="text" id="total_pago" readonly class="text-center no-border col-12" style="font-size: 20px; font-weight: bold; box-shadow: 0 0 10px #000;
                border-radius: 10px;" value="{{ importe_pagado.total_importe|default:0 }}">
        </div>
        <div class="col-3 col-xs-3 col-sm-3 col-md-3 col-lg-2 col-xl-2 col-xxl-1 text-center">
            Total<br>
            <input type="text" id="total_pago" readonly class="text-center no-border col-12" style="font-size: 20px; font-weight: bold; box-shadow: 0 0 10px #000;
                border-radius: 10px;" value="{{ importe_total.total_importe|default:0 }}">
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="col-11 col-xs-11 col-sm-11 col-md-9 col-lg-9 col-xl-7 col-xxl-6">
            <table class="table cuadro caption-top">
                <caption>
                    <h3>Comanda de la mesa - {{ mesa_id }}</h3>
                </caption>
                <thead>
                    <tr class="text-center">
                        <th class="col-4">
                            Producto
                        </th>
                        <th class="col-2">
                            Cantidad
                        </th>
                        <th class="col-2">
                            Precio
                        </th>
                        <th class="col-2">
                            Importe
                        </th>
                        <th class="col-2 align-middle">
                            Estatus
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for mesa in elementos %}
                    <tr>
                        <td>
                            {{mesa.nom_producto}}
                        </td>
                        <td class="text-center">
                            {{mesa.cantidad}}
                        </td>
                        <td class="text-end">
                            {{mesa.precio_unitario}}
                        </td>
                        <td class="text-end">
                            <input type="text" class="form-control text-end no-border" value="{{mesa.importe}}" readonly
                                name="importe_{{mesa.id}}" id="id_importe_{{mesa.id}}" style="padding: 0;">
                        </td>
                        <td class="text-center">
                            {% if mesa.estatus == 1 %}
                            Elaborando
                            {% elif mesa.estatus == 2 %}
                            Por entregar
                            {% elif mesa.estatus == 3 %}
                            Por pagar
                            {% else %}
                            Pagado
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</form>
{% endblock %}

pedido/templates/pedido/respaldo/comanda_create.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
<h1>Nueva Comanda</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <h2>Detalles</h2>
    {{ detalle_formset.management_form }}
    {% for form in detalle_formset %}
    {{ form.as_table }}
    {% endfor %}

    <button type="submit">Guardar</button>
</form>
{% endblock %}

pedido/templates/pedido/respaldo/comanda_detail.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block contenido %}
  <h1>Detalle de Comanda</h1>
  <p>Mesa: {{ comanda.mesa }}</p>
  <p>Observación: {{ comanda.observacion }}</p>
  <h2>Detalles</h2>
  <table>
    <thead>
      <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio unitario</th>
        <th>Observación</th>
      </tr>
    </thead>
    <tbody>
      {% for detalle in comanda.detalle_set.all %}
        <tr>
          <td>{{ detalle.producto }}</td>
          <td>{{ detalle.cantidad }}</td>
          <td>{{ detalle.precio_unitario }}</td>
          <td>{{ detalle.observacion }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}